name: Check
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - run: pip install ruff

      - run: ruff check

  mypy:
    name: MyPy
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install mypy
        run: pip install mypy==1.8.0

      - name: Run
        run: mypy .